(function(g){var window=this;var Iua=function(a,b){var c=[];g.em(b,function(a){var b;try{b=g.kI.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.NF(b)&&c.push(a):c.push(a)},a);
return c},Jua=function(a,b){var c=Iua(a,b);
(0,g.K)(c,function(a){g.kI.prototype.remove.call(this,a)},a)},Kua=function(){var a=g.PK;
Jua(a,a.g.Gd(!0))},Lua=function(a){return a.H?a.F+((0,g.C)()-a.A)/1E3:a.F},v9=function(a){g.Ti("cloudview",a)},w9=function(a){g.Au.call(this,"ScreenServiceProxy");
this.Qc=a;this.o=[];this.o.push(this.Qc.$_s("screenChange",(0,g.z)(this.IO,this)));this.o.push(this.Qc.$_s("onlineScreenChange",(0,g.z)(this.cL,this)))},Mua=function(a){v9("setApiReady_ "+a);
g.oa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},x9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},Nua=function(a){g.ys[a]&&(a=g.ys[a],(0,g.K)(a,function(a){g.ws[a]&&delete g.ws[a]}),a.length=0)},y9=function(){return g.u("yt.mdx.remote.connection_")},z9=function(a){g.oa("yt.mdx.remote.connectData_",a,void 0)},Oua=function(a){g.oa("yt.mdx.remote.currentScreenId_",a,void 0)},A9=function(){return g.u("yt.mdx.remote.currentScreenId_")},C9=function(){if(!B9){var a=g.u("yt.mdx.remote.screenService_");
B9=a?new w9(a):null}return B9},D9=function(a){g.oa("yt.mdx.remote.cloudview.initializing_",a,void 0)},E9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},F9=function(a){v9("setCastInstalled_ "+a);
g.RK("yt-remote-cast-installed",a)},G9=function(a){g.Ti("cloudview",a)},Pua=function(a,b){x9().init(a,b)},H9=function(){return!!g.SK("yt-remote-cast-installed")},Qua=function(){v9("dispose");
var a=x9();a&&a.dispose();g.oa("yt.mdx.remote.cloudview.instance_",null,void 0);Mua(!1);g.As(I9);I9.length=0},Rua=function(){var a=window.document.createElement("a");
g.wo(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.ec(a)},Sua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Tua=function(a){var b=g.us();
if(b)if(b.clear(a),a)Nua(a);else for(var c in g.ys)Nua(c)},J9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},L9=function(a){var b=y9();
z9(null);a||Oua("");g.oa("yt.mdx.remote.connection_",a,void 0);K9&&((0,g.K)(K9,function(b){b(a)}),K9.length=0);
b&&!a?g.Ds("yt-remote-connection-change",!1):!b&&a&&g.Ds("yt-remote-connection-change",!0)},Uua=function(){return g.u("yt.mdx.remote.connectData_")},M9=function(){var a=A9();
if(!a)return null;var b=C9().Ld();return g.Fm(b,a)},Vua=function(a,b){F9(!0);
D9(!1);Pua(a,function(a){a?(Mua(!0),g.Cs("yt-remote-cast2-api-ready")):(G9("Failed to initialize cast API."),F9(!1),g.TK("yt-remote-cast-available"),g.TK("yt-remote-cast-receiver"),Qua());b(a)})},Wua=function(){return H9()?x9()?x9().getCastSession():(G9("getCastSelector: Cast is not initialized."),null):(G9("getCastSelector: Cast API is not installed!"),null)},Xua=function(){var a=Rua(),b=window.document.getElementById(a),c=b&&g.zc(b,"loaded");
c||b&&!c||(b=Sua(a,function(){g.zc(b,"loaded")||(g.Ac(b,"loaded","true"),g.Cs(a),g.zk(g.za(Tua,a),0))}))},Yua=function(a){return(0,g.M)(a,function(a){return{key:a.id,
name:a.name}})},Zua=function(){if(g.moa){var a=2,b=g.Fa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ka("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ha,c)}},O9=function(a,b){A9();
M9()&&M9();Oua(a.id);var c=new g.AY(N9,a,J9());c.connect(b,Uua());c.subscribe("beforeDisconnect",function(a){g.Ds("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y9()&&(y9(),L9(null))});
L9(c)},P9=function(){var a=g.TL();
if(!a)return null;var b=C9().Ld();return g.Fm(b,a)},Q9=function(a){g.Ti("remote",a)},R9=function(){var a=y9();
return!!a&&3!=a.getProxyState()},S9=function(){E9()?x9().stopSession():G9("stopSession called before API ready.");
var a=y9();a&&(a.disconnect(1),L9(null))},$ua=function(){var a;
a=C9().Qc.$_gos();var b=M9();b&&y9()&&(g.Em(a,b)||a.push(b));return Yua(a)},U9=function(a,b){g.ts.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.$h;this.A=this.o=null;this.H=(0,g.z)(this.pJ,this);this.F=(0,g.z)(this.ck,this);this.G=(0,g.z)(this.oJ,this);this.J=(0,g.z)(this.CJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Yr,this),ava(this))):c=3;0!=c&&(b?this.Yr(c):g.zk((0,g.z)(function(){this.Yr(c)},this),0));
var d=Wua();d&&T9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},V9=function(a){return new g.ae(a.B.getPlayerContextData())},bva=function(a,b,c,d,e){var f=V9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.ee(f,b,d);g.p(c)&&(g.ce(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);W9(a,"setPlaylist",l);e||X9(a,f)},ava=function(a){(0,g.K)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.vL,a),this))},a)},cva=function(a){(0,g.K)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y9=function(a,b){50>a.C.zc()&&g.bi(a.C,b)},Z9=function(a,b,c){var d=V9(a);
g.ce(d,c);-1E3!=d.g&&(d.g=b);X9(a,d)},W9=function(a,b,c){a.B.sendMessage(b,c)},X9=function(a,b){cva(a);
a.B.setPlayerContextData(g.fe(b));ava(a)},T9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.ck(null));
a.A=b;a.A&&($9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.ck(a.A.media[0]))},dva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=V9(a);b.contentId!=d.videoId&&$9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.ce(d,a.o.getEstimatedTime());X9(a,d)}else $9("No cast media video. Ignoring state update.")},$9=function(a){g.Ti("CP",a)},a$=function(a,b,c){return(0,g.z)(function(a){this.Vb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Vb("Retrying "+b+" using MDx browser channel."),W9(this,b,c))},a)},eva=function(a){var b=!1;
x9()||(a=new g.RT(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.RK("yt-remote-cast-available",a);g.Ds("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){v9("onReceiverSelected: "+a.friendlyName);
g.RK("yt-remote-cast-receiver",a);g.Ds("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){v9("onReceiverResumed: "+a.friendlyName);
g.RK("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){v9("onSessionChange: "+g.aj(a));
a||g.TK("yt-remote-cast-receiver");g.Ds("yt-remote-cast2-session-change",a)}),g.oa("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
v9("cloudview.createSingleton_: "+b);return b},fva=function(){var a=0<=g.Jd.search(/\ (CrMo|Chrome|CriOS)\//);
return g.Tp||a},b$=function(a,b){E9()?x9().setConnectedScreenStatus(a,b):G9("setConnectedScreenStatus called before ready.")},gva=function(){v9("clearCurrentReceiver");
g.TK("yt-remote-cast-receiver")},hva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Zua();a({command:"cast.sender.init"});return}}if(window.chrome&&window.isSecureContext)if(Zua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Da();55<=b?a="55":50<=b&&(a="50");g.Ka("//www.gstatic.com/eureka/clank"+a+g.Ia,g.Ha)}else g.La(0);else g.Ha()},iva=function(a){a?(g.RK("yt-remote-session-app",a.app),g.RK("yt-remote-session-name",a.name)):(g.TK("yt-remote-session-app"),g.TK("yt-remote-session-name"));
g.oa("yt.mdx.remote.channelParams_",a,void 0)},jva=function(){var a=J9();
if(g.Cb(a)){var a=g.SL(),b=g.SK("yt-remote-session-name")||"",c=g.SK("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.oa("yt.mdx.remote.channelParams_",a,void 0)}},kva=function(){var a=P9();
a?(Q9("Resume connection to: "+g.aj(a)),O9(a,0)):(g.aM(),gva(),Q9("Skipping connecting because no session screen found."))},lva=function(a){Q9("remote.onCastSessionChange_: "+g.aj(a));
if(a){var b=M9();b&&b.id==a.id?b$(b.id,"YouTube TV"):(b&&S9(),O9(a,1))}else y9()&&S9()},mva=function(){var a=$ua(),b=M9();
b||(b=P9());return g.ze(a,function(a){return b&&g.Yi(b,a.key)?!0:!1})},nva=function(){var a=g.SK("yt-remote-cast-receiver");
return a?a.friendlyName:null},ova=function(a,b,c,d){fva()?eva(b)&&(D9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Vua(a,c):(window.__onGCastApiAvailable=function(b,d){b?Vua(a,c):(G9("Failed to load cast API: "+d),F9(!1),D9(!1),g.TK("yt-remote-cast-available"),g.TK("yt-remote-cast-receiver"),Qua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Xua():hva())):v9("Cannot initialize because not running Chrome")},
pva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.zf(a)||"";b&&(this.port=":"+b);this.A=g.yf(a)||"";a=g.Jd;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.dc(a,"10.0")&&(this.o=!1))},c$=function(){var a=mva();
!a&&H9()&&nva()&&(a={key:"cast-selector-receiver",name:nva()});return a},qva=function(){var a=$ua();
H9()&&g.SK("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},rva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.PK&&Kua();g.VL();N9||(N9=new pva,g.cM()&&(N9.g="/api/loungedev"));K9||(K9=g.u("yt.mdx.remote.deferredProxies_")||[],g.oa("yt.mdx.remote.deferredProxies_",K9,void 0));jva();var c=C9();if(!c){var d=new g.ZO(N9);g.oa("yt.mdx.remote.screenService_",d,void 0);c=C9();ova(a,d,function(a){a?A9()&&b$(A9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Ds("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.oa("yt.mdx.remote.initialized_",!0,void 0),Q9("Initializing: "+g.Dz(b)),d$.push(g.zs("yt-remote-cast2-availability-change",function(){g.Ds("yt-remote-receiver-availability-change")})),d$.push(g.zs("yt-remote-cast2-receiver-selected",function(){z9(null);
g.Ds("yt-remote-auto-connect","cast-selector-receiver")})),d$.push(g.zs("yt-remote-cast2-receiver-resumed",function(){g.Ds("yt-remote-receiver-resumed","cast-selector-receiver")})),d$.push(g.zs("yt-remote-cast2-session-change",lva)),d$.push(g.zs("yt-remote-connection-change",function(a){a?b$(A9(),"YouTube TV"):P9()||(b$(null,null),gva())})),a=J9(),b.isAuto&&(a.id+="#dial"),g.Uf("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,Q9(" -- with channel params: "+g.Dz(a)),
iva(a),c.start(),A9()||kva())},e$=function(a,b,c){g.H.call(this);
this.H=a;this.Y=b;b.addEventListener("onVolumeChange",this.Om,this);b.addEventListener("onCaptionsTrackListChanged",this.Fx,this);b.addEventListener("captionschanged",this.rx,this);b.addEventListener("captionssettingschanged",this.sr,this);b.addEventListener("videoplayerreset",this.fk,this);b.addEventListener("mdxautoplaycancel",this.Wt,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.Sx,this);c.subscribe("remotePlayerChange",this.ek,this);c.subscribe("remoteQueueChange",
this.fk,this);c.subscribe("autoplayUpNext",this.ox,this);c.subscribe("previousNextChange",this.Px,this);c.subscribe("nowAutoplaying",this.Ix,this);c.subscribe("autoplayDismissed",this.mx,this);this.suggestion=null;this.D=new g.gG(64);this.o=new g.tz(this.jz,500,this);g.J(this,this.o);this.A=new g.tz(this.kz,1E3,this);g.J(this,this.A);this.B={};this.G=new g.tz(this.Az,1E3,this);g.J(this,this.G);this.F=new g.wz(this.CQ,1E3,this);g.J(this,this.F);this.J=g.x;this.sr();this.fk();this.ek()},f$=function(a,
b){var c=a.H,d=a.Y.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},sva=function(a){f$(a,0);
a.o.stop();g$(a,new g.gG(64))},j$=function(a,b){if(h$(a)&&!a.C){var c=null;
b&&(c={style:a.Y.Gk()},g.Ib(c,b));a.g.bz(i$(a),c);a.B=V9(a.g).o}},k$=function(a,b){var c=a.Y.Ue();
c?bva(a.g,i$(a),b,c.Jd(),c.listId.toString()):bva(a.g,i$(a),b);g$(a,new g.gG(1))},tva=function(a,b){if(b){var c=a.Y.Sc("captions","tracklist",{ew:1});
c&&c.length?(a.Y.ue("captions","track",b),a.C=!1):(a.Y.Ck("captions"),a.C=!0)}else a.Y.ue("captions","track",{})},h$=function(a){return V9(a.g).videoId==i$(a)},i$=function(a){return a.Y.getVideoData().videoId},g$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.G(b,2);if(d!=g.G(a.D,2)){var e=a.Y;(e=g.OS(e.app,e.playerType||1))&&g.RV(e,d)}a.D=b;uva(a.H,c,b)}},l$=function(){H9()?x9()?E9()?(v9("Requesting cast selector."),x9().requestSession()):(v9("Wait for cast API to be ready to request the session."),I9.push(g.zs("yt-remote-cast2-api-ready",l$))):G9("requestCastSelector: Cast is not initialized."):G9("requestCastSelector: Cast API is not installed!")},m$=function(a){g.gv.call(this,a);
this.A={key:g.Dm(),name:g.L("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.gG(64);this.H=0},uva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.ad(c,b))},n$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)S9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Ue();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Tb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.$z(),0),currentTime:a.g.getCurrentTime()}}else c=null;Q9("Connecting to: "+g.Dz(b));"cast-selector-receiver"==b.key?(z9(c||null),c=c||null,E9()?x9().setLaunchParams(c):G9("setLaunchParams called before ready.")):!c&&R9()&&A9()==b.key?g.Ds("yt-remote-connection-change",
!0):(S9(),z9(c||null),c=C9().Ld(),(c=g.Fm(c,b.key))&&O9(c,1))}};
g.B(w9,g.Au);g.h=w9.prototype;g.h.Ld=function(a){return this.Qc.$_gs(a)};
g.h.contains=function(a){return!!this.Qc.$_c(a)};
g.h.get=function(a){return this.Qc.$_g(a)};
g.h.start=function(){this.Qc.$_st()};
g.h.Mn=function(a,b,c){this.Qc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Qc.$_r(a,b,c)};
g.h.An=function(a,b,c,d){this.Qc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Qc.$_ubk(this.o[a]);this.o.length=0;this.Qc=null;w9.N.R.call(this)};
g.h.IO=function(){this.U("screenChange")};
g.h.cL=function(){this.U("onlineScreenChange")};
var B9=null,I9=[],K9=null,N9=null;g.B(U9,g.ts);g.h=U9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,a$(this,"play")):W9(this,"play"),Z9(this,1,g.de(V9(this))),this.U("remotePlayerChange")):Y9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,a$(this,"pause")):W9(this,"pause"),Z9(this,2,g.de(V9(this))),this.U("remotePlayerChange")):Y9(this,this.pause)};
g.h.Pz=function(a){if(1==this.g){if(this.o){var b=V9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,a$(this,"seekTo",{newTime:a}))}else W9(this,"seekTo",{newTime:a});Z9(this,3,a);this.U("remotePlayerChange")}else Y9(this,g.za(this.Pz,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,a$(this,"stopVideo")):W9(this,"stopVideo");var a=V9(this);a.index=-1;a.videoId="";g.be(a);X9(this,a);this.U("remotePlayerChange")}else Y9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=V9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){$9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Vb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){$9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Vb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W9(this,"setVolume",e)}c.muted=b;c.volume=a;X9(this,c)}else Y9(this,g.za(this.setVolume,a,b))};
g.h.bz=function(a,b){if(1==this.g){var c=V9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Dz(b.style),g.Ib(d,c.o));W9(this,"setSubtitlesTrack",d);X9(this,c)}else Y9(this,g.za(this.bz,a,b))};
g.h.Xr=function(a,b){if(1==this.g){W9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Hc.id});var c=V9(this);c.audioTrackId=b.Hc.id;X9(this,c)}else Y9(this,g.za(this.Xr,a,b))};
g.h.Oz=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.ee(c,a,b);X9(this,c)}W9(this,"previous")}else Y9(this,g.za(this.Oz,a,b))};
g.h.Nz=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.ee(c,a,b);X9(this,c)}W9(this,"next")}else Y9(this,g.za(this.Nz,a,b))};
g.h.Eu=function(){1==this.g?W9(this,"dismissAutoplay"):Y9(this,this.Eu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}U9.N.dispose.call(this)};
g.h.R=function(){cva(this);this.B=null;this.C.clear();T9(this,null);U9.N.R.call(this)};
g.h.Yr=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.ci(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.vL=function(a,b){this.U(a,b)};
g.h.pJ=function(a){if(!a)this.ck(null),T9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=V9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,X9(this,b)}};
g.h.ck=function(a){$9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),dva(this),this.U("remotePlayerChange")};
g.h.oJ=function(a){a?(dva(this),this.U("remotePlayerChange")):this.ck(null)};
g.h.CJ=function(){var a=Wua();a&&T9(this,a)};
g.h.Vb=function(a){g.Ti("CP",a)};
var d$=[];g.h=pva.prototype;g.h.sh=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Hf(d+a,b||{})};
g.h.Wr=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Gb:g.za(this.DO,c,!0),onError:g.za(this.CO,d),ad:g.za(this.EO,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.BB(a,c)};
g.h.DO=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.CO=function(a,b){a(Error("Request error: "+b.status))};
g.h.EO=function(a){a(Error("request timed out"))};
g.B(e$,g.H);g.h=e$.prototype;
g.h.R=function(){e$.N.R.call(this);this.o.stop();this.A.stop();this.J();this.Y.removeEventListener("onVolumeChange",this.Om,this);this.Y.removeEventListener("onCaptionsTrackListChanged",this.Fx,this);this.Y.removeEventListener("captionschanged",this.rx,this);this.Y.removeEventListener("videoplayerreset",this.fk,this);this.Y.removeEventListener("captionssettingschanged",this.sr,this);this.Y.removeEventListener("mdxautoplaycancel",this.Wt,this);this.g.unsubscribe("proxyStateChange",this.Sx,this);this.g.unsubscribe("remotePlayerChange",
this.ek,this);this.g.unsubscribe("remoteQueueChange",this.fk,this);this.g.unsubscribe("autoplayUpNext",this.ox,this);this.g.unsubscribe("previousNextChange",this.Px,this);this.g.unsubscribe("nowAutoplaying",this.Ix,this);this.g.unsubscribe("autoplayDismissed",this.mx,this);this.g=this.H=null};
g.h.GA=function(a,b){2==this.g.g||(h$(this)?this.KF.apply(this,arguments):this.GF.apply(this,arguments))};
g.h.rx=function(a){this.GA("control_subtitles_set_track",g.Cb(a)?null:a)};
g.h.sr=function(){var a=this.Y.Sc("captions","track");g.Cb(a)||j$(this,a)};
g.h.GF=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":k$(this,this.Y.getCurrentTime());break;case "control_seek":k$(this,c[0]);break;case "control_subtitles_set_track":j$(this,c[0]);break;case "control_set_audio_track":c=c[0],h$(this)&&this.g.Xr(i$(this),c)}};
g.h.KF=function(a,b){if(1081!=V9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":V9(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.si(c[0],c[1]);break;case "control_subtitles_set_track":j$(this,c[0]);break;case "control_set_audio_track":c=c[0],h$(this)&&this.g.Xr(i$(this),c)}}};
g.h.Om=function(a){if(h$(this)){this.g.unsubscribe("remotePlayerChange",this.ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=V9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.ek,this)}};
g.h.Fx=function(){g.Cb(this.B)||tva(this,this.B);this.C=!1};
g.h.Sx=function(a,b){this.A.stop();2==b&&this.kz()};
g.h.ek=function(){if(h$(this)){this.o.stop();var a=V9(this.g);switch(a.g){case 1081:g$(this,new g.gG(8));break;case 1:this.jz();g$(this,new g.gG(8));break;case 1083:case 3:g$(this,new g.gG(9));break;case 0:g$(this,new g.gG(2));this.F.stop();f$(this,this.Y.getVideoData().lengthSeconds);break;case 1082:g$(this,new g.gG(4));break;case 2:g$(this,new g.gG(4));f$(this,g.de(a));break;case -1:g$(this,new g.gG(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.L("YTP_MDX_PLAYER_ERROR")},g$(this,
new g.gG(128,a))}var a=V9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,tva(this,a));a=V9(this.g);-1==a.volume||Math.round(this.Y.getVolume())==a.volume&&this.Y.Td()==a.muted||this.G.isActive()||this.Az()}else sva(this)};
g.h.Px=function(){this.Y.U("mdxpreviousnextchange")};
g.h.fk=function(){h$(this)||sva(this)};
g.h.Wt=function(){this.g.Eu()};
g.h.ox=function(a){a&&(a=g.BB("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},Gb:(0,g.z)(this.tM,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.tM=function(a,b){var c=new g.nU({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Y.U("mdxautoplayupnext",c)};
g.h.Ix=function(a){(0,window.isNaN)(a)||this.Y.U("mdxnowautoplaying",a)};
g.h.mx=function(){this.Y.U("mdxautoplaycanceled")};
g.h.CQ=function(a,b){-1==V9(this.g).g?k$(this,a):b&&this.g.Pz(a)};
g.h.Az=function(){if(h$(this)){var a=V9(this.g);this.Y.removeEventListener("onVolumeChange",this.Om,this);a.muted?this.Y.mute():this.Y.kg();this.Y.setVolume(a.volume);this.Y.addEventListener("onVolumeChange",this.Om,this)}};
g.h.jz=function(){this.o.stop();if(!this.g.isDisposed()){var a=V9(this.g);a.jb()&&g$(this,new g.gG(8));f$(this,g.de(a));this.o.start()}};
g.h.kz=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.B(m$,g.gv);g.h=m$.prototype;g.h.create=function(){rva("embedded"==g.X(this.g).g);this.D.push(g.zs("yt-remote-before-disconnect",this.lJ,this));this.D.push(g.zs("yt-remote-connection-change",this.FL,this));this.D.push(g.zs("yt-remote-receiver-availability-change",this.Qx,this));this.D.push(g.zs("yt-remote-auto-connect",this.CL,this));this.D.push(g.zs("yt-remote-receiver-resumed",this.BL,this));this.Qx()};
g.h.load=function(){this.g.Ko();m$.N.load.call(this);this.C=new e$(this,this.g,this.o);var a;a=(a=Uua())?a.currentTime:0;var b=R9()?new U9(y9(),void 0):null;0==a&&b&&(a=g.de(V9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));uva(this,this.F,this.F);g.D2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Gd(this.C,this.o);this.o=this.C=null;m$.N.unload.call(this);g.D2(this.g.app,5)};
g.h.R=function(){g.As(this.D);m$.N.R.call(this)};
g.h.Kk=function(a,b){this.loaded&&this.C.GA.apply(this.C,arguments)};
g.h.lF=function(){return this.loaded?this.C.suggestion:null};
g.h.qf=function(){return this.o?V9(this.o).qf:!1};
g.h.hasNext=function(){return this.o?V9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.hQ=function(){var a=V9(this.o),b=this.g.getVideoData(),c=this.g.Ah(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.C)()-a.A)/1E3:a.B;var l=1>=Lua(a)-this.getCurrentTime(),m=a.J,n=Lua(a),a=0<a.C?a.C+((0,g.C)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.iQ=function(){this.o&&this.o.Nz()};
g.h.jQ=function(){this.o&&this.o.Oz()};
g.h.lJ=function(a){1==a&&(this.J=this.o?V9(this.o):null)};
g.h.FL=function(){var a=R9()?new U9(y9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Fd(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Mc(g.de(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Qx=function(){this.G=[this.A].concat(qva());var a=c$()||this.A;n$(this,a);this.g.va("onMdxReceiversChange")};
g.h.CL=function(){var a=c$();n$(this,a)};
g.h.BL=function(){this.B=c$()};
g.h.gQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l$():n$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l$(),!0):!1}};
g.h.kQ=function(){W9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.oe=function(){return!1};
window._exportCheck==g.Ca&&g.oa("ytmod.player.remote",m$,void 0);})(_yt_player);
